#!/bin/sh

set -e ; python3.11 script/beachland.py > src/data/venues/beachland.json; echo "✅ Beachland" ; python3.11 script/grog-shop.py > src/data/venues/grog-shop.json; echo "✅ Grog Shop" ; python3.11 script/mahalls.py > src/data/venues/mahalls.json; echo "✅ Mahalls" ; python3.11 script/agora.py > src/data/venues/agora.json; echo "✅ Agora" ; python3.11 script/hob.py > src/data/venues/hob.json; echo "✅ HOB" 
